// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginLocalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLocalRequest) Reset() {
	*x = LoginLocalRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLocalRequest) ProtoMessage() {}

func (x *LoginLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLocalRequest.ProtoReflect.Descriptor instead.
func (*LoginLocalRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginLocalRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginLocalRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginLocalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	User          *UserSummary           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLocalResponse) Reset() {
	*x = LoginLocalResponse{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLocalResponse) ProtoMessage() {}

func (x *LoginLocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLocalResponse.ProtoReflect.Descriptor instead.
func (*LoginLocalResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginLocalResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *LoginLocalResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type GoogleVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleVerifyRequest) Reset() {
	*x = GoogleVerifyRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleVerifyRequest) ProtoMessage() {}

func (x *GoogleVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleVerifyRequest.ProtoReflect.Descriptor instead.
func (*GoogleVerifyRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GoogleVerifyRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type GoogleVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	User          *UserSummary           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleVerifyResponse) Reset() {
	*x = GoogleVerifyResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleVerifyResponse) ProtoMessage() {}

func (x *GoogleVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleVerifyResponse.ProtoReflect.Descriptor instead.
func (*GoogleVerifyResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GoogleVerifyResponse) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *GoogleVerifyResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterBusinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   string                 `protobuf:"bytes,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBusinessRequest) Reset() {
	*x = RegisterBusinessRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBusinessRequest) ProtoMessage() {}

func (x *RegisterBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBusinessRequest.ProtoReflect.Descriptor instead.
func (*RegisterBusinessRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterBusinessRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *RegisterBusinessRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterBusinessRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterBusinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBusinessResponse) Reset() {
	*x = RegisterBusinessResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBusinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBusinessResponse) ProtoMessage() {}

func (x *RegisterBusinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBusinessResponse.ProtoReflect.Descriptor instead.
func (*RegisterBusinessResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterBusinessResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   string                 `protobuf:"bytes,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAdminRequest) Reset() {
	*x = RegisterAdminRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAdminRequest) ProtoMessage() {}

func (x *RegisterAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAdminRequest.ProtoReflect.Descriptor instead.
func (*RegisterAdminRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterAdminRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *RegisterAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAdminResponse) Reset() {
	*x = RegisterAdminResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAdminResponse) ProtoMessage() {}

func (x *RegisterAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAdminResponse.ProtoReflect.Descriptor instead.
func (*RegisterAdminResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAdminResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type RequestPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetRequest) Reset() {
	*x = RequestPasswordResetRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetRequest) ProtoMessage() {}

func (x *RequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RequestPasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RequestPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetResponse) Reset() {
	*x = RequestPasswordResetResponse{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetResponse) ProtoMessage() {}

func (x *RequestPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

type ListAuditLogsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeTsRfc3339 string                 `protobuf:"bytes,2,opt,name=before_ts_rfc3339,json=beforeTsRfc3339,proto3" json:"before_ts_rfc3339,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ListAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditLogsRequest) GetBeforeTsRfc3339() string {
	if x != nil {
		return x.BeforeTsRfc3339
	}
	return ""
}

type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TsRfc3339     string                 `protobuf:"bytes,2,opt,name=ts_rfc3339,json=tsRfc3339,proto3" json:"ts_rfc3339,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	ActorUserId   string                 `protobuf:"bytes,5,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	DetailJson    string                 `protobuf:"bytes,8,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *AuditLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLogEntry) GetTsRfc3339() string {
	if x != nil {
		return x.TsRfc3339
	}
	return ""
}

func (x *AuditLogEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditLogEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AuditLogEntry) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *AuditLogEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuditLogEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditLogEntry) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditLogEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ListAuditLogsResponse) GetEntries() []*AuditLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type InsertAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ActorUserId   string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	DetailJson    string                 `protobuf:"bytes,6,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertAuditLogRequest) Reset() {
	*x = InsertAuditLogRequest{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAuditLogRequest) ProtoMessage() {}

func (x *InsertAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAuditLogRequest.ProtoReflect.Descriptor instead.
func (*InsertAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *InsertAuditLogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InsertAuditLogRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InsertAuditLogRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *InsertAuditLogRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InsertAuditLogRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InsertAuditLogRequest) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

type InsertAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertAuditLogResponse) Reset() {
	*x = InsertAuditLogResponse{}
	mi := &file_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAuditLogResponse) ProtoMessage() {}

func (x *InsertAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAuditLogResponse.ProtoReflect.Descriptor instead.
func (*InsertAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{17}
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"E\n" +
	"\x11LoginLocalRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"G\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"M\n" +
	"\x12LoginLocalResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.auth.UserSummaryR\x04user\"0\n" +
	"\x13GoogleVerifyRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"O\n" +
	"\x14GoogleVerifyResponse\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.auth.UserSummaryR\x04user\"o\n" +
	"\x17RegisterBusinessRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\tR\vadminUserId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"A\n" +
	"\x18RegisterBusinessResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.auth.UserSummaryR\x04user\"l\n" +
	"\x14RegisterAdminRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\tR\vadminUserId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\">\n" +
	"\x15RegisterAdminResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.auth.UserSummaryR\x04user\"3\n" +
	"\x1bRequestPasswordResetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x1e\n" +
	"\x1cRequestPasswordResetResponse\"O\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x17\n" +
	"\x15ResetPasswordResponse\"X\n" +
	"\x14ListAuditLogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12*\n" +
	"\x11before_ts_rfc3339\x18\x02 \x01(\tR\x0fbeforeTsRfc3339\"\xd3\x01\n" +
	"\rAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ts_rfc3339\x18\x02 \x01(\tR\ttsRfc3339\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\"\n" +
	"\ractor_user_id\x18\x05 \x01(\tR\vactorUserId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x1f\n" +
	"\vdetail_json\x18\b \x01(\tR\n" +
	"detailJson\"F\n" +
	"\x15ListAuditLogsResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.auth.AuditLogEntryR\aentries\"\xac\x01\n" +
	"\x15InsertAuditLogRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x1f\n" +
	"\vdetail_json\x18\x06 \x01(\tR\n" +
	"detailJson\"\x18\n" +
	"\x16InsertAuditLogResponse2\xf6\x04\n" +
	"\x0fUserAuthService\x12?\n" +
	"\n" +
	"LoginLocal\x12\x17.auth.LoginLocalRequest\x1a\x18.auth.LoginLocalResponse\x12E\n" +
	"\fGoogleVerify\x12\x19.auth.GoogleVerifyRequest\x1a\x1a.auth.GoogleVerifyResponse\x12Q\n" +
	"\x10RegisterBusiness\x12\x1d.auth.RegisterBusinessRequest\x1a\x1e.auth.RegisterBusinessResponse\x12H\n" +
	"\rRegisterAdmin\x12\x1a.auth.RegisterAdminRequest\x1a\x1b.auth.RegisterAdminResponse\x12]\n" +
	"\x14RequestPasswordReset\x12!.auth.RequestPasswordResetRequest\x1a\".auth.RequestPasswordResetResponse\x12H\n" +
	"\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponse\x12H\n" +
	"\rListAuditLogs\x12\x1a.auth.ListAuditLogsRequest\x1a\x1b.auth.ListAuditLogsResponse\x12K\n" +
	"\x0eInsertAuditLog\x12\x1b.auth.InsertAuditLogRequest\x1a\x1c.auth.InsertAuditLogResponseB\x18Z\x16shared/proto/auth;authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_auth_proto_goTypes = []any{
	(*LoginLocalRequest)(nil),            // 0: auth.LoginLocalRequest
	(*UserSummary)(nil),                  // 1: auth.UserSummary
	(*LoginLocalResponse)(nil),           // 2: auth.LoginLocalResponse
	(*GoogleVerifyRequest)(nil),          // 3: auth.GoogleVerifyRequest
	(*GoogleVerifyResponse)(nil),         // 4: auth.GoogleVerifyResponse
	(*RegisterBusinessRequest)(nil),      // 5: auth.RegisterBusinessRequest
	(*RegisterBusinessResponse)(nil),     // 6: auth.RegisterBusinessResponse
	(*RegisterAdminRequest)(nil),         // 7: auth.RegisterAdminRequest
	(*RegisterAdminResponse)(nil),        // 8: auth.RegisterAdminResponse
	(*RequestPasswordResetRequest)(nil),  // 9: auth.RequestPasswordResetRequest
	(*RequestPasswordResetResponse)(nil), // 10: auth.RequestPasswordResetResponse
	(*ResetPasswordRequest)(nil),         // 11: auth.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),        // 12: auth.ResetPasswordResponse
	(*ListAuditLogsRequest)(nil),         // 13: auth.ListAuditLogsRequest
	(*AuditLogEntry)(nil),                // 14: auth.AuditLogEntry
	(*ListAuditLogsResponse)(nil),        // 15: auth.ListAuditLogsResponse
	(*InsertAuditLogRequest)(nil),        // 16: auth.InsertAuditLogRequest
	(*InsertAuditLogResponse)(nil),       // 17: auth.InsertAuditLogResponse
}
var file_auth_proto_depIdxs = []int32{
	1,  // 0: auth.LoginLocalResponse.user:type_name -> auth.UserSummary
	1,  // 1: auth.GoogleVerifyResponse.user:type_name -> auth.UserSummary
	1,  // 2: auth.RegisterBusinessResponse.user:type_name -> auth.UserSummary
	1,  // 3: auth.RegisterAdminResponse.user:type_name -> auth.UserSummary
	14, // 4: auth.ListAuditLogsResponse.entries:type_name -> auth.AuditLogEntry
	0,  // 5: auth.UserAuthService.LoginLocal:input_type -> auth.LoginLocalRequest
	3,  // 6: auth.UserAuthService.GoogleVerify:input_type -> auth.GoogleVerifyRequest
	5,  // 7: auth.UserAuthService.RegisterBusiness:input_type -> auth.RegisterBusinessRequest
	7,  // 8: auth.UserAuthService.RegisterAdmin:input_type -> auth.RegisterAdminRequest
	9,  // 9: auth.UserAuthService.RequestPasswordReset:input_type -> auth.RequestPasswordResetRequest
	11, // 10: auth.UserAuthService.ResetPassword:input_type -> auth.ResetPasswordRequest
	13, // 11: auth.UserAuthService.ListAuditLogs:input_type -> auth.ListAuditLogsRequest
	16, // 12: auth.UserAuthService.InsertAuditLog:input_type -> auth.InsertAuditLogRequest
	2,  // 13: auth.UserAuthService.LoginLocal:output_type -> auth.LoginLocalResponse
	4,  // 14: auth.UserAuthService.GoogleVerify:output_type -> auth.GoogleVerifyResponse
	6,  // 15: auth.UserAuthService.RegisterBusiness:output_type -> auth.RegisterBusinessResponse
	8,  // 16: auth.UserAuthService.RegisterAdmin:output_type -> auth.RegisterAdminResponse
	10, // 17: auth.UserAuthService.RequestPasswordReset:output_type -> auth.RequestPasswordResetResponse
	12, // 18: auth.UserAuthService.ResetPassword:output_type -> auth.ResetPasswordResponse
	15, // 19: auth.UserAuthService.ListAuditLogs:output_type -> auth.ListAuditLogsResponse
	17, // 20: auth.UserAuthService.InsertAuditLog:output_type -> auth.InsertAuditLogResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
