// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: finance.proto

package finance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinanceService_GetMyTransactions_FullMethodName    = "/finance.FinanceService/GetMyTransactions"
	FinanceService_GetGlobalRevenue_FullMethodName     = "/finance.FinanceService/GetGlobalRevenue"
	FinanceService_GetRegionalAnalytics_FullMethodName = "/finance.FinanceService/GetRegionalAnalytics"
	FinanceService_GetCategoryInsights_FullMethodName  = "/finance.FinanceService/GetCategoryInsights"
)

// FinanceServiceClient is the client API for FinanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceServiceClient interface {
	GetMyTransactions(ctx context.Context, in *GetMyTransactionsRequest, opts ...grpc.CallOption) (*GetMyTransactionsResponse, error)
	GetGlobalRevenue(ctx context.Context, in *GetGlobalRevenueRequest, opts ...grpc.CallOption) (*GetGlobalRevenueResponse, error)
	GetRegionalAnalytics(ctx context.Context, in *GetRegionalAnalyticsRequest, opts ...grpc.CallOption) (*GetRegionalAnalyticsResponse, error)
	GetCategoryInsights(ctx context.Context, in *GetCategoryInsightsRequest, opts ...grpc.CallOption) (*GetCategoryInsightsResponse, error)
}

type financeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceServiceClient(cc grpc.ClientConnInterface) FinanceServiceClient {
	return &financeServiceClient{cc}
}

func (c *financeServiceClient) GetMyTransactions(ctx context.Context, in *GetMyTransactionsRequest, opts ...grpc.CallOption) (*GetMyTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyTransactionsResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetMyTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetGlobalRevenue(ctx context.Context, in *GetGlobalRevenueRequest, opts ...grpc.CallOption) (*GetGlobalRevenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalRevenueResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetGlobalRevenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetRegionalAnalytics(ctx context.Context, in *GetRegionalAnalyticsRequest, opts ...grpc.CallOption) (*GetRegionalAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegionalAnalyticsResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetRegionalAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetCategoryInsights(ctx context.Context, in *GetCategoryInsightsRequest, opts ...grpc.CallOption) (*GetCategoryInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryInsightsResponse)
	err := c.cc.Invoke(ctx, FinanceService_GetCategoryInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServiceServer is the server API for FinanceService service.
// All implementations must embed UnimplementedFinanceServiceServer
// for forward compatibility.
type FinanceServiceServer interface {
	GetMyTransactions(context.Context, *GetMyTransactionsRequest) (*GetMyTransactionsResponse, error)
	GetGlobalRevenue(context.Context, *GetGlobalRevenueRequest) (*GetGlobalRevenueResponse, error)
	GetRegionalAnalytics(context.Context, *GetRegionalAnalyticsRequest) (*GetRegionalAnalyticsResponse, error)
	GetCategoryInsights(context.Context, *GetCategoryInsightsRequest) (*GetCategoryInsightsResponse, error)
	mustEmbedUnimplementedFinanceServiceServer()
}

// UnimplementedFinanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinanceServiceServer struct{}

func (UnimplementedFinanceServiceServer) GetMyTransactions(context.Context, *GetMyTransactionsRequest) (*GetMyTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTransactions not implemented")
}
func (UnimplementedFinanceServiceServer) GetGlobalRevenue(context.Context, *GetGlobalRevenueRequest) (*GetGlobalRevenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalRevenue not implemented")
}
func (UnimplementedFinanceServiceServer) GetRegionalAnalytics(context.Context, *GetRegionalAnalyticsRequest) (*GetRegionalAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegionalAnalytics not implemented")
}
func (UnimplementedFinanceServiceServer) GetCategoryInsights(context.Context, *GetCategoryInsightsRequest) (*GetCategoryInsightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryInsights not implemented")
}
func (UnimplementedFinanceServiceServer) mustEmbedUnimplementedFinanceServiceServer() {}
func (UnimplementedFinanceServiceServer) testEmbeddedByValue()                        {}

// UnsafeFinanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceServiceServer will
// result in compilation errors.
type UnsafeFinanceServiceServer interface {
	mustEmbedUnimplementedFinanceServiceServer()
}

func RegisterFinanceServiceServer(s grpc.ServiceRegistrar, srv FinanceServiceServer) {
	// If the following call panics, it indicates UnimplementedFinanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinanceService_ServiceDesc, srv)
}

func _FinanceService_GetMyTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetMyTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetMyTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetMyTransactions(ctx, req.(*GetMyTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetGlobalRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetGlobalRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetGlobalRevenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetGlobalRevenue(ctx, req.(*GetGlobalRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetRegionalAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionalAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetRegionalAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetRegionalAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetRegionalAnalytics(ctx, req.(*GetRegionalAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetCategoryInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetCategoryInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinanceService_GetCategoryInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetCategoryInsights(ctx, req.(*GetCategoryInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceService_ServiceDesc is the grpc.ServiceDesc for FinanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.FinanceService",
	HandlerType: (*FinanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyTransactions",
			Handler:    _FinanceService_GetMyTransactions_Handler,
		},
		{
			MethodName: "GetGlobalRevenue",
			Handler:    _FinanceService_GetGlobalRevenue_Handler,
		},
		{
			MethodName: "GetRegionalAnalytics",
			Handler:    _FinanceService_GetRegionalAnalytics_Handler,
		},
		{
			MethodName: "GetCategoryInsights",
			Handler:    _FinanceService_GetCategoryInsights_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance.proto",
}
