// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: finance.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents      int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Type             string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // credit | debit
	Region           string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	SourceTripId     string                 `protobuf:"bytes,8,opt,name=source_trip_id,json=sourceTripId,proto3" json:"source_trip_id,omitempty"`
	CreatedAtRfc3339 string                 `protobuf:"bytes,9,opt,name=created_at_rfc3339,json=createdAtRfc3339,proto3" json:"created_at_rfc3339,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetSourceTripId() string {
	if x != nil {
		return x.SourceTripId
	}
	return ""
}

func (x *Transaction) GetCreatedAtRfc3339() string {
	if x != nil {
		return x.CreatedAtRfc3339
	}
	return ""
}

type GetMyTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyTransactionsRequest) Reset() {
	*x = GetMyTransactionsRequest{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTransactionsRequest) ProtoMessage() {}

func (x *GetMyTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetMyTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMyTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMyTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyTransactionsResponse) Reset() {
	*x = GetMyTransactionsResponse{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTransactionsResponse) ProtoMessage() {}

func (x *GetMyTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetMyTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetGlobalRevenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRfc3339   string                 `protobuf:"bytes,1,opt,name=from_rfc3339,json=fromRfc3339,proto3" json:"from_rfc3339,omitempty"`
	ToRfc3339     string                 `protobuf:"bytes,2,opt,name=to_rfc3339,json=toRfc3339,proto3" json:"to_rfc3339,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalRevenueRequest) Reset() {
	*x = GetGlobalRevenueRequest{}
	mi := &file_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalRevenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRevenueRequest) ProtoMessage() {}

func (x *GetGlobalRevenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRevenueRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalRevenueRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{3}
}

func (x *GetGlobalRevenueRequest) GetFromRfc3339() string {
	if x != nil {
		return x.FromRfc3339
	}
	return ""
}

func (x *GetGlobalRevenueRequest) GetToRfc3339() string {
	if x != nil {
		return x.ToRfc3339
	}
	return ""
}

type RevenuePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenuePoint) Reset() {
	*x = RevenuePoint{}
	mi := &file_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenuePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenuePoint) ProtoMessage() {}

func (x *RevenuePoint) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenuePoint.ProtoReflect.Descriptor instead.
func (*RevenuePoint) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{4}
}

func (x *RevenuePoint) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *RevenuePoint) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type GetGlobalRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCents    int64                  `protobuf:"varint,1,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Trend         []*RevenuePoint        `protobuf:"bytes,3,rep,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalRevenueResponse) Reset() {
	*x = GetGlobalRevenueResponse{}
	mi := &file_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRevenueResponse) ProtoMessage() {}

func (x *GetGlobalRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRevenueResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalRevenueResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{5}
}

func (x *GetGlobalRevenueResponse) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *GetGlobalRevenueResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetGlobalRevenueResponse) GetTrend() []*RevenuePoint {
	if x != nil {
		return x.Trend
	}
	return nil
}

type GetRegionalAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromRfc3339   string                 `protobuf:"bytes,1,opt,name=from_rfc3339,json=fromRfc3339,proto3" json:"from_rfc3339,omitempty"`
	ToRfc3339     string                 `protobuf:"bytes,2,opt,name=to_rfc3339,json=toRfc3339,proto3" json:"to_rfc3339,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionalAnalyticsRequest) Reset() {
	*x = GetRegionalAnalyticsRequest{}
	mi := &file_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionalAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionalAnalyticsRequest) ProtoMessage() {}

func (x *GetRegionalAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionalAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetRegionalAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{6}
}

func (x *GetRegionalAnalyticsRequest) GetFromRfc3339() string {
	if x != nil {
		return x.FromRfc3339
	}
	return ""
}

func (x *GetRegionalAnalyticsRequest) GetToRfc3339() string {
	if x != nil {
		return x.ToRfc3339
	}
	return ""
}

type RegionTotal struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Region           string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	AmountCents      int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	TransactionCount int32                  `protobuf:"varint,3,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegionTotal) Reset() {
	*x = RegionTotal{}
	mi := &file_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionTotal) ProtoMessage() {}

func (x *RegionTotal) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionTotal.ProtoReflect.Descriptor instead.
func (*RegionTotal) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{7}
}

func (x *RegionTotal) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegionTotal) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *RegionTotal) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type GetRegionalAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*RegionTotal         `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionalAnalyticsResponse) Reset() {
	*x = GetRegionalAnalyticsResponse{}
	mi := &file_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionalAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionalAnalyticsResponse) ProtoMessage() {}

func (x *GetRegionalAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionalAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetRegionalAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{8}
}

func (x *GetRegionalAnalyticsResponse) GetRegions() []*RegionTotal {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *GetRegionalAnalyticsResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetCategoryInsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryInsightsRequest) Reset() {
	*x = GetCategoryInsightsRequest{}
	mi := &file_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryInsightsRequest) ProtoMessage() {}

func (x *GetCategoryInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryInsightsRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryInsightsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{9}
}

type CategoryInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInsight) Reset() {
	*x = CategoryInsight{}
	mi := &file_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInsight) ProtoMessage() {}

func (x *CategoryInsight) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInsight.ProtoReflect.Descriptor instead.
func (*CategoryInsight) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryInsight) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryInsight) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CategoryInsight) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetCategoryInsightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryInsight     `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryInsightsResponse) Reset() {
	*x = GetCategoryInsightsResponse{}
	mi := &file_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryInsightsResponse) ProtoMessage() {}

func (x *GetCategoryInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryInsightsResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryInsightsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{11}
}

func (x *GetCategoryInsightsResponse) GetCategories() []*CategoryInsight {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetCategoryInsightsResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\"\x8d\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12$\n" +
	"\x0esource_trip_id\x18\b \x01(\tR\fsourceTripId\x12,\n" +
	"\x12created_at_rfc3339\x18\t \x01(\tR\x10createdAtRfc3339\"I\n" +
	"\x18GetMyTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"U\n" +
	"\x19GetMyTransactionsResponse\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.finance.TransactionR\ftransactions\"[\n" +
	"\x17GetGlobalRevenueRequest\x12!\n" +
	"\ffrom_rfc3339\x18\x01 \x01(\tR\vfromRfc3339\x12\x1d\n" +
	"\n" +
	"to_rfc3339\x18\x02 \x01(\tR\ttoRfc3339\"I\n" +
	"\fRevenuePoint\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\"\x84\x01\n" +
	"\x18GetGlobalRevenueResponse\x12\x1f\n" +
	"\vtotal_cents\x18\x01 \x01(\x03R\n" +
	"totalCents\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12+\n" +
	"\x05trend\x18\x03 \x03(\v2\x15.finance.RevenuePointR\x05trend\"_\n" +
	"\x1bGetRegionalAnalyticsRequest\x12!\n" +
	"\ffrom_rfc3339\x18\x01 \x01(\tR\vfromRfc3339\x12\x1d\n" +
	"\n" +
	"to_rfc3339\x18\x02 \x01(\tR\ttoRfc3339\"u\n" +
	"\vRegionTotal\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12+\n" +
	"\x11transaction_count\x18\x03 \x01(\x05R\x10transactionCount\"j\n" +
	"\x1cGetRegionalAnalyticsResponse\x12.\n" +
	"\aregions\x18\x01 \x03(\v2\x14.finance.RegionTotalR\aregions\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x1c\n" +
	"\x1aGetCategoryInsightsRequest\"f\n" +
	"\x0fCategoryInsight\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"s\n" +
	"\x1bGetCategoryInsightsResponse\x128\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x18.finance.CategoryInsightR\n" +
	"categories\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency2\x8c\x03\n" +
	"\x0eFinanceService\x12Z\n" +
	"\x11GetMyTransactions\x12!.finance.GetMyTransactionsRequest\x1a\".finance.GetMyTransactionsResponse\x12W\n" +
	"\x10GetGlobalRevenue\x12 .finance.GetGlobalRevenueRequest\x1a!.finance.GetGlobalRevenueResponse\x12c\n" +
	"\x14GetRegionalAnalytics\x12$.finance.GetRegionalAnalyticsRequest\x1a%.finance.GetRegionalAnalyticsResponse\x12`\n" +
	"\x13GetCategoryInsights\x12#.finance.GetCategoryInsightsRequest\x1a$.finance.GetCategoryInsightsResponseB\x1eZ\x1cshared/proto/finance;financeb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_finance_proto_goTypes = []any{
	(*Transaction)(nil),                  // 0: finance.Transaction
	(*GetMyTransactionsRequest)(nil),     // 1: finance.GetMyTransactionsRequest
	(*GetMyTransactionsResponse)(nil),    // 2: finance.GetMyTransactionsResponse
	(*GetGlobalRevenueRequest)(nil),      // 3: finance.GetGlobalRevenueRequest
	(*RevenuePoint)(nil),                 // 4: finance.RevenuePoint
	(*GetGlobalRevenueResponse)(nil),     // 5: finance.GetGlobalRevenueResponse
	(*GetRegionalAnalyticsRequest)(nil),  // 6: finance.GetRegionalAnalyticsRequest
	(*RegionTotal)(nil),                  // 7: finance.RegionTotal
	(*GetRegionalAnalyticsResponse)(nil), // 8: finance.GetRegionalAnalyticsResponse
	(*GetCategoryInsightsRequest)(nil),   // 9: finance.GetCategoryInsightsRequest
	(*CategoryInsight)(nil),              // 10: finance.CategoryInsight
	(*GetCategoryInsightsResponse)(nil),  // 11: finance.GetCategoryInsightsResponse
}
var file_finance_proto_depIdxs = []int32{
	0,  // 0: finance.GetMyTransactionsResponse.transactions:type_name -> finance.Transaction
	4,  // 1: finance.GetGlobalRevenueResponse.trend:type_name -> finance.RevenuePoint
	7,  // 2: finance.GetRegionalAnalyticsResponse.regions:type_name -> finance.RegionTotal
	10, // 3: finance.GetCategoryInsightsResponse.categories:type_name -> finance.CategoryInsight
	1,  // 4: finance.FinanceService.GetMyTransactions:input_type -> finance.GetMyTransactionsRequest
	3,  // 5: finance.FinanceService.GetGlobalRevenue:input_type -> finance.GetGlobalRevenueRequest
	6,  // 6: finance.FinanceService.GetRegionalAnalytics:input_type -> finance.GetRegionalAnalyticsRequest
	9,  // 7: finance.FinanceService.GetCategoryInsights:input_type -> finance.GetCategoryInsightsRequest
	2,  // 8: finance.FinanceService.GetMyTransactions:output_type -> finance.GetMyTransactionsResponse
	5,  // 9: finance.FinanceService.GetGlobalRevenue:output_type -> finance.GetGlobalRevenueResponse
	8,  // 10: finance.FinanceService.GetRegionalAnalytics:output_type -> finance.GetRegionalAnalyticsResponse
	11, // 11: finance.FinanceService.GetCategoryInsights:output_type -> finance.GetCategoryInsightsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
